
version: '3'

services:
    web:
        image: nginx-alpine
        ports:
            - "80:80"
    shadowsocks:
        image: shadowsocks-alpine
        ports:
            - "8388:8388"
        volumes:
            - /data/docker/shadowsocks/shadowsocks.json:/etc/shadowsocks.json

             
