# 基于Ubuntu的tomcat镜像

# 基于官方ubuntu镜像
FROM ubuntu

# 维护者
MAINTAINER feifeigd "502207456@qq.com"

RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update

ENTRYPOINT java -version
